//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ScreenshotDetails
    {
        public long Id { get; set; }
        public string Fk_DeviceId { get; set; }
        public string Screenshot1 { get; set; }
        public string Screenshot2 { get; set; }
        public string Screenshot3 { get; set; }
        public string Screenshot4 { get; set; }
        public string Screenshot5 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Tbl_Devices Tbl_Devices { get; set; }
    }
}
