//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Devices
    {
        public Tbl_Devices()
        {
            this.Tbl_ScreenshotDetails = new HashSet<Tbl_ScreenshotDetails>();
        }
    
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string DeviceName { get; set; }
        public Nullable<bool> DeviceStatus { get; set; }
        public string DeviceIp { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsShutdownDevice { get; set; }
    
        public virtual ICollection<Tbl_ScreenshotDetails> Tbl_ScreenshotDetails { get; set; }
    }
}
