//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon.DMS.DataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Device()
        {
            this.Tbl_ScreenshotDetails = new HashSet<Tbl_ScreenshotDetails>();
        }
    
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceStatus { get; set; }
        public string DeviceIp { get; set; }
        public Nullable<int> ScreenShotInterval { get; set; }
        public Nullable<bool> IsShutdownDevice { get; set; }
        public Nullable<bool> IsPause { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ScreenshotDetails> Tbl_ScreenshotDetails { get; set; }
    }
}
