//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon.DMS.DataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ScreenshotDetails
    {
        public long Id { get; set; }
        public string Fk_DeviceId { get; set; }
        public string ScreenshotPath { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
    
        public virtual Tbl_Device Tbl_Device { get; set; }
    }
}
